language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
matrix:
  allow_failures:
    - php: nightly
before_script: composer install
script:
  - mkdir -p build/logs  
  - ./vendor/bin/phpunit -c phpunit.xml
after_script:
  - php vendor/bin/php-coveralls -v

